CREATE TABLE `partecipanti_globali` ( `ID_DIPENDENTE` INT NOT NULL, `PCT_UTILIZZO` DECIMAL NOT NULL, `MANSIONE` VARCHAR(20) NULL DEFAULT NULL , `COSTO` DECIMAL NULL DEFAULT NULL , PRIMARY KEY (`ID_DIPENDENTE`)) ENGINE = InnoDB;

CREATE TABLE `commesse` ( `COD_COMMESSA` VARCHAR(50) NOT NULL , `PCT_COMPATIBILITA` FLOAT NOT NULL DEFAULT '100' , `NOTE` TEXT NULL , `GIUSTIFICATIVO` LONGBLOB NULL , `GIUSTIFICATIVO_FILENAME` VARCHAR(255) NULL , PRIMARY KEY (`COD_COMMESSA`)) ENGINE = InnoDB;

DELETE FROM `progetti_commesse`;

ALTER TABLE `progetti_commesse`
  DROP `PCT_COMPATIBILITA`,
  DROP `NOTE`,
  DROP `GIUSTIFICATIVO`,
  DROP `GIUSTIFICATIVO_FILENAME`;

ALTER TABLE `progetti_commesse` ADD `ORE_PREVISTE` DECIMAL NOT NULL DEFAULT '0' AFTER `COD_COMMESSA`;

ALTER TABLE `progetti_commesse` ADD FOREIGN KEY (`COD_COMMESSA`) REFERENCES `commesse`(`COD_COMMESSA`) ON DELETE RESTRICT ON UPDATE RESTRICT;
