CREATE TABLE `partecipanti_globali` ( `ID_DIPENDENTE` INT NOT NULL, `PCT_UTILIZZO` DECIMAL NOT NULL, `MANSIONE` VARCHAR(20) NULL DEFAULT NULL , `COSTO` DECIMAL NULL DEFAULT NULL , PRIMARY KEY (`ID_DIPENDENTE`)) ENGINE = InnoDB;

#